[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spaceboard"

version = "1.1.5"

keywords = ["space", "dashboard", "tui", "neo"]

description = "A simple, open-source and self-hosted TUI dashboard to visualize NASA Near Earth Objects (NEOs) data."

readme = "README.md"

requires-python = ">=3.11"

license = "MIT"

authors = [
    { name = "Alessio Parolini", email = "alepar.ap9@gmail.com"}
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Environment :: Console",
]

dependencies = [
    "httpx>=0.27.0",
    "python-dotenv>=1.0.0",
    "rich>=13.0.0",
    "textual>=0.70.0",
    "pyfiglet>=1.0.2"
]

[project.urls]
Homepage = "https://github.com/alessioparolini2011/spaceboard"

[tool.setuptools]
packages = { find = { where = ["src"] } }

[tool.setuptools.package-data]
spaceboard = ["tcss/*.tcss"]

[project.scripts]
spaceboard = "spaceboard.main:start"